#!/usr/bin/env python

#USRP1 Address Definition
MAC_ADDR_CSMA_ON = 65
MAC_ADDR_CSMA_TH = 66
MAC_ADDR_CSMA_BT_1L = 67   
MAC_ADDR_CSMA_BT_1H = 68   
MAC_ADDR_CSMA_BT_2L = 69   
MAC_ADDR_CSMA_BT_2H = 70   
MAC_ADDR_CSMA_BT_3L = 71   
MAC_ADDR_CSMA_BT_3H = 72   
MAC_ADDR_CSMA_BT_4L = 73   
MAC_ADDR_CSMA_BT_4H = 74   
MAC_ADDR_CSMA_BT_5L = 75   
MAC_ADDR_CSMA_BT_5H = 76   

#MAC Parameter Default Values
MAC_CSMA_TH_DEF = 30
MAC_CSMA_MIN_BE = 3

MAC_CSMA_UNIT_BT = 640 # Unit = us
